### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by dralucindaodonto** [07akioni/lyla#15]
I already use lyla  in a big project, everything works  exceptionally well, but now I am trying to use it in a new project and I keep getting this error :

D:\projetos\ledoctor2\whatsappweb\node_modules\.pnpm\lyla@0.6.8\node_modules\lyla\lib\index.js:528
    const xhr = new XMLHttpRequest();
                ^
is something broken  ?

Regards

**Comment by 07akioni** [comment]
I think you may use it in non browser environment.
