### ISSUE TITLE
[feat request] adapter-fetch

### ISSUE THREAD

**Issue by dragon-fish** [07akioni/lyla#18]
Add fetch adapter. So that lyla can be use on both modern browsers and Node.js

FYI https://github.com/moegirlwiki/wiki-saikou/tree/8040694aab89e164e1c1a2e211f96b2f259111a6/src/modules/lyla-adapter-fetch

**Comment by dragon-fish** [comment]
In the end, I created a fetch based package myself 😂

https://www.npmjs.com/package/fexios

**Comment by 07akioni** [comment]
We won't support for fetch adapter since it can't support `onUploadProgress` and is cumbersome to implement `onDownloadProgress`.

Also, there's no alternative for `xhr.readyState === xhr.HEADERS_RECEIVED`'s hook.
