### ISSUE TITLE
[feat request] export options when createInstance

### ISSUE THREAD

**Issue by dragon-fish** [07akioni/lyla#19]
Export options here:

https://github.com/07akioni/lyla/blob/4f6152b0382a1f28fd50cfe1bd7c709c0fce7a70/packages/core/src/core.ts#L534-L550

So that we can modify options or hooks after instance created.

**e.g.**

```ts
const { lyla, options } = createLyla({ /* ... */ })
options.hooks ??= {}
options.hooks.onBeforeRequest ??= []
options.hooks.onBeforeRequest.push((ctx) => {
  // ...
})
```

It's kind of like `axios.interceptors` does:

```ts
const request = axios.create({ /* ... */ })
request.interceptors.request.use((ctx) => {
  // ...
})
```

**Comment by 07akioni** [comment]
Lyla don't allow modify instance after it's created.

For a better programming pattern, it's recommended to initialized all hooks before you create lyla instance.

**Comment by 07akioni** [comment]
If you want to initialize different instances based on same options. You should do like this:

```
const baseOptions: LylaRequestOptions<C> & { context: C } = { context: C, ... }

const { lyla: lyla1 } = createLyla(baseOptions, extendedOptions1)

const { lyla: lyla2 } = createLyla(baseOptions, extendedOptions2)
```
