### ISSUE TITLE
[question] vite build fail on the browser

### ISSUE THREAD

**Issue by xuchao996** [07akioni/lyla#20]
hi, 

when i use this in vite, the lastst version had 2 issue。
![image](https://github.com/07akioni/lyla/assets/44614061/54078d4e-4dc6-4f02-b2f5-21ce39acd3ea)

1. i find use node version not browser version when i use it on the browser.
2. using a destructuring pipline is a error, and build fail.

thanks.

**Comment by 07akioni** [comment]
You should only use `@lylajs/web` if you only want to support browser environment.
