### ISSUE TITLE
feature: 新功能 关于 uniapp

### ISSUE THREAD

**Issue by chengazhen** [07akioni/lyla#21]
是否考虑增加一个uniapp的模块呢 ? 通过逻辑观察 wx 模块的基本可以兼容到 uniapp

**Comment by 07akioni** [comment]
欢迎 PR，我对 uniapp 不太熟

**Comment by chengazhen** [comment]
关于基于 lylajs 实现会有以下问题。请教一下是否有解决思路。
![image](https://github.com/07akioni/lyla/assets/52627267/9128877f-9ca4-4241-9da2-9e90fbc80182)
关于这两段代码，对于  if (method === 'GET' && body) { } 校验代码段是不是应该放在 adapter 里面自行决定校验？

举个例子，在小程序里面不管是get和post传参都是放在data对象（相当于浏览器端的post 请求的body，可以理解为小程序里面不管什么请求参数都是放在body里面的）。

### 问题（只在get请求里面存在）
1. 在这个get方法里面如果使用query，那么就会遇到小程序里面没有 urlSearchParams 字段的报错。
```ts
export function getRepoList(data: { status: string }) {
  return lyla<Item>({
    method: 'get',
    url: '/pet/findByStatus',
    // body: data
    query: data
  })
}
```
![image](https://github.com/07akioni/lyla/assets/52627267/e2357e32-89b1-4cb7-9a42-25d34810c97c)

2. 如果在get方法使用 json 或者 body 就会遇到下面的错误。因为 options.json 最终会被合并到了 body 里面。body 和 json 对于get 请求是互斥的。
```ts

export function getRepoList(data: { status: string }) {
  return lyla<Item>({
    method: 'get',
    url: '/pet/findByStatus',
    body: data
    // query: data
  })
}
```
![image](https://github.com/07akioni/lyla/assets/52627267/2fc4f4fb-e1c2-40f9-904e-e6791d9f4b0e)

**Comment by chengazhen** [comment]
这个是我写的一个仓库，里面有复现问题的demo，需要在小程序的环境下可以复现对应的问题

**Comment by 07akioni** [comment]
我能理解你说的问题，可以加一个选项来处理

**Comment by 07akioni** [comment]
发布了 1.11.0，增加了一个选项叫 allowGetBody，设为 true 的话可以把 get + body 的组合发出去

**Comment by 07akioni** [comment]
uniapp 的想要你可以 copy 一个 wx 的包改吧改吧提个 PR
