### ISSUE TITLE
ts 类型错误

### ISSUE THREAD

**Issue by chengazhen** [07akioni/lyla#22]
## 下面代码中使用了 body 传递参数的时候会出现类型报错
在跳转到对应的类型声明时是
```ts
export interface LylaAdapterMeta {
    method: LylaMethod;
    requestBody: any | undefined;
    responseType: 'arraybuffer' | 'blob' | 'text';
    responseBody: any;
    networkErrorDetail: any;
    responseDetail: any;
    progressDetail: any;
    originalRequest: any;
}
```

### 以下是错误提示
对象字面量只能指定已知属性，并且“name”不在类型“ArrayBuffer”中。ts(2353)
types.d.ts(22, 5): 所需类型来自属性 "body"，在此处的 "LylaRequestOptions<null, LylaAdapterMeta>" 类型上声明该属性
```ts
lyla({
  url: '/api/lyla',
  method: 'post',
  body: {
    name: 'lyla'
  }
})
```

**Comment by chengazhen** [comment]
![image](https://github.com/07akioni/lyla/assets/52627267/7862ba15-8b2d-40b7-b31b-a7107c02a522)
查看代码发现此处对 json 进行了json字符串格式化, 想请教一下这个的作用是干什么的呢

**Comment by 07akioni** [comment]
> ![image](https://private-user-images.githubusercontent.com/52627267/294137593-7862ba15-8b2d-40b7-b31b-a7107c02a522.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTAwOTAsIm5iZiI6MTcxMzA4OTc5MCwicGF0aCI6Ii81MjYyNzI2Ny8yOTQxMzc1OTMtNzg2MmJhMTUtOGIyZC00MGI3LWIzMWItYTcxMDdjMDJhNTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDEwMTYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDNkZmFkZmFiMWJkYjdiYmJlYzc1NzllYTI4MTM5ZGJlMjI1YmQ4M2JlZTlkMDRlZDk5YTc5NDY1OWU2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W9zHpcMqu4rXFZcM2K53_g8ICqDv2XMd6u5C0yahKqM) 查看代码发现此处对 json 进行了json字符串格式化, 想请教一下这个的作用是干什么的呢

默认情况下会把 json 转化成 string 的 json，如果你不是想直接传 body：用字符串、用 blob 之类的，你需要用 json
